version: "3.8" #versione di docker-compose#

services:
  db: #servizio del DB con postgresSQL#
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: postgres
    container_name: postgresqlte
    restart: always
    ports:
      - "54320:5432"
    environment: #variabili che vanno inizializzate del DB #
      POSTGRES_USER: mattia
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mattiaDB
    volumes: #volumi per salvare perm i dati#
      - dati_pg:/var/lib/postgresql/data
    networks:
      - miaRete
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mattia.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - miaRete

volumes:
  dati_pg:
  pgadmin-data:
networks:
  miaRete:
    driver: bridge